apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-t6hn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-t6hn
    app.kubernetes.io/part-of: tkrw-pr714-0075-0050-app
  name: devfile-sample-t6hn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-t6hn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-t6hn
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0050-tenant/tkrw-pr714-0075-0050-app/devfile-sample-t6hn@sha256:599cc642cf5def3e83a90c864ff360291ecf8b1759cb2a6c86b59d7491bdd14a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
