apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-t6hn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0050-tenant/tkrw-pr714-0075-0050-app/devfile-sample-t6hn@sha256:599cc642cf5def3e83a90c864ff360291ecf8b1759cb2a6c86b59d7491bdd14a
        name: my-nodejs
        resources: {}
status: {}
